### ISSUE TITLE
Typo: FDQN should be FQDN (Fully Qualified Domain Name)

### ISSUE THREAD

**Issue by vincec-msft** [tvrprasad/sspi-client#2]
In a couple places in src_js/fdqn.js, including the file name. :)

**Comment by tvrprasad** [comment]
Huh, I always read it and wrote it as fdqn for some reason. In fact I read the issue as fqdn should be fdqn and kept looking for instances of fqdn to fix :)

Fixed the typo.

**Comment by tvrprasad** [comment]
https://github.com/tvrprasad/sspi-client/commit/f79b334e3832b2f7869bfca0b1cc30a018a8d7ad
