### ISSUE TITLE
Server methods?

### ISSUE THREAD

**Issue by simon-p-r** [tvrprasad/sspi-client#39]
Is there any plans to include server-side methods?  Node is really missing a native module that does this properly.

Thanks
Simon

**Comment by tvrprasad** [comment]
No plans for server methods at this time. I developed this module primarily to support Integrated Authentication in https://github.com/tediousjs/tedious/.

**Comment by tvrprasad** [comment]
@simon-p-r btw, there is this module that supports some server-side scenarios - https://www.npmjs.com/package/node-sspi. May be that'll meet your requirement.

**Comment by simon-p-r** [comment]
@tvrprasad that module is not fit for purpose!
